version: "3"
services:
    db:
        image: postgres
        volumes:
        - postgres-data:/var/lib/postgresql/data
        ports:
        - 8001:5432
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=testdb
        restart: unless-stopped

    order_service:
        build: orderService/.
        ports: 
        - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: admin
        depends_on:
        - "db"
    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: dc297@dc297.io
            PGADMIN_DEFAULT_PASSWORD: dc297
            PGADMIN_LISTEN_PORT: 80
        ports:
        - "5000:80"
        volumes:
        - pgadmin-data:/var/lib/pgadmin
volumes:
    postgres-data:
    pgadmin-data:
